import 'package:flutter/material.dart';

IconData iconFromName(String name) {
  const icons = <String, IconData>{
    'account_balance': Icons.account_balance,
    'account_balance_wallet': Icons.account_balance_wallet,
    'payments': Icons.payments,
    'work_outline': Icons.work_outline,
    'storefront': Icons.storefront,
    'sell': Icons.sell,
    'card_giftcard': Icons.card_giftcard,
    'restaurant': Icons.restaurant,
    'shopping_cart': Icons.shopping_cart,
    'directions_car': Icons.directions_car,
    'local_gas_station': Icons.local_gas_station,
    'home': Icons.home,
    'receipt_long': Icons.receipt_long,
    'local_hospital': Icons.local_hospital,
    'school': Icons.school,
    'movie': Icons.movie,
    'shopping_bag': Icons.shopping_bag,
    'savings': Icons.savings,
    'more_horiz': Icons.more_horiz,
    'currency_bitcoin': Icons.currency_bitcoin,
    'cash': Icons.payments,
    'flight': Icons.flight_takeoff,
    'fitness_center': Icons.fitness_center,
    'pets': Icons.pets,
    'phone_iphone': Icons.phone_iphone,
    'laptop': Icons.laptop,
    'favorite': Icons.favorite,
    'celebration': Icons.celebration,
    'local_shipping': Icons.local_shipping,
    'menu_book': Icons.menu_book,
    'beach_access': Icons.beach_access,
    'attach_money': Icons.attach_money,
    'trending_up': Icons.trending_up,
  };
  return icons[name] ?? Icons.category;
}